doc:
  property:
  - mongodb: ''
  - jumpscale: ''
  - branch: ''
links:
  consume:
  - argname: mongodb
    auto: true
    max: 100
    min: '1'
    role: mongodb
  parent:
    auto: true
    optional: false
    role: jumpscale
    argname: jumpscale
recurring: []
