links:
    parent:
        role: golang
        auto: True
        optional: False


    consume:
        -   role: syncthing
            argname: syncthing
            auto: False
            min: 1
            max: 1

doc:
    properties:
        - syncthing: ''
        - golang: ''